# GitHub Pages config

url: https://typescriptlibs.org
title: TypeScriptLibs
description: TypeScript Libraries and Tools
author: Â© TypeScriptLibs

email: bug@typescriptlibs.org
github_username: typescriptlibs
rss: rss

github:
  private: true

header_pages:
  - support/index.md
  - index.md

include:
  - LICENSE.md
  - package/tsl-apple-cloudkit.md
  - package/tsl-mastodon-api.md
  - package/tst.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

show_excerpts: false

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: classic
